### ISSUE TITLE
Detect unload when editing templates and automatically unlock.

### ISSUE THREAD

**Issue by benloh** [netcreateorg/netcreate-2018#219]
Noted by Joshua in #200:
If you go to edit a template, then navigate away in some way (e.g., reloading the page), then the network remains locked and there is no way to unlock it without a restart. Can we use the navigate away to trigger the unlock in one manner?

**Comment by benloh** [comment]
Fixed by 3244155c32f1280a44c01f7ec7b54e42abc56e65

**Comment by benloh** [comment]
@jdanish This should be fixed by the latest push 3244155c32f1280a44c01f7ec7b54e42abc56e65  Please test and verify and close if it's addressed.

**Comment by jdanish** [comment]
I still see it happening?  

Steps:

1. Open network
2. Click more / edit template
3. Click to edit edges
4. Reload page
5. You can't edit nodes or the template

**Comment by jdanish** [comment]
Nevermind. Tried npm ci and then re-ran and now seems good.

**Comment by benloh** [comment]
There may be some edge conditions I didn't quite catch.  It's rather finicky because there are so many variations on sequence.  I tried to simplify it as much as I could.

But the main reason it probably failed for you the first time is because you need to quit and restart the server for the server changes to take effect -- the hot-reload only works for the client side files.

**Comment by jdanish** [comment]
Yeah - I restarted but this one was definitely the npm ci I think.
